### ISSUE TITLE
not having docker 

### ISSUE THREAD

**Issue by hassanisaadi** [cucapra/approx-vision#3]
Hi,
I don't have docker. Instead, I have singularity (I am not root on the machine). I tried to look at the singularity document to run the docker image files but I couldn't. Do you have any advice on how to run the docker image with singularity?
Thanks

**Comment by mbuckler** [comment]
Hey!

Looks like you're in luck, they have an official guide on how to run docker images on singularity: https://singularity.lbl.gov/docs-docker. It sounds like you might have already tried that, so I also found this unofficial guide which seems useful: https://hpc.wsu.edu/programmers-guide/docker-via-singularity/

In case you have another machine which you can run docker on (say a personal laptop) then you can use this code to convert docker images to singularity images: https://github.com/singularityware/docker2singularity

**Comment by mbuckler** [comment]
Did any of these guides solve your issue @hassanisaadi ?

If so please let us know what worked so we can close this issue.

**Comment by hassanisaadi** [comment]
Yep. I installed it on my local machine and everything went well. I used docker on my machine.

Thanks.
