### ISSUE TITLE
Can't figure out a script to feed my own image directory

### ISSUE THREAD

**Issue by TolgaAktas** [cucapra/approx-vision#4]
I have a directory full of 346 images in /approx-image/datasets folder that I created. I wanted to write a script file to have the first (reverse) pipeline to iterate over every image and reverse it but I can't seem to figure out the way it's done in other datasets. how can I do that please?

**Comment by sampsyo** [comment]
Hi! @mbuckler will have the proper answers, but to get things started, maybe you can point to the specific point along the [recipe in the FAQ](https://github.com/cucapra/approx-vision/wiki/Getting-Started-FAQ) where you got stuck?

**Comment by mbuckler** [comment]
Hi @TolgaAktas! Yes, as @sampsyo  says, [https://github.com/cucapra/approx-vision/wiki/Getting-Started-FAQ](FAQ) is the place to start. Have you successfully converted a single file from JPEG to RAW as directed in the first set of instructions?  If so, you can move on to the next step which is simply writing a script to run the converter for every image. Examples of these scripts for other datasets can be found in [https://github.com/cucapra/approx-vision/tree/master/pipelines](approx-vision/pipelines).

**Comment by mbuckler** [comment]
Closed for inactivity
